apiVersion: {{ .Values.backend.apiVersion }}
kind: {{ .Values.backend.kind }}
metadata:
  name: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: {{ .Values.backend.name }}
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          volumeMounts:
            - mountPath: /app
              name: backend-volume

      volumes:
        - name: backend-volume
          hostPath:
            path: /path/to/your/app/directory  # Шлях до вашої директорії з додатком

---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
