apiVersion: {{ .Values.frontend.apiVersion }}
kind: {{ .Values.frontend.kind }}
metadata:
  name: {{ .Values.frontend.name }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      containers:
        - name: {{ .Values.frontend.name }}
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: frontend-volume

      volumes:
        - name: frontend-volume
          hostPath:
            path: /path/to/your/frontend/directory  # Шлях до вашої директорії з фронтендом

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
