backend:
  image: kravchuchka/backend
  apiVersion: apps/v1
  kind: Deployment
  name: backend
  replicas: 1
  containerPort: 3000

frontend:
  image: kravchuchka/frontend
  apiVersion: apps/v1
  kind: Deployment
  name: frontend
  replicas: 1
  containerPort: 80

postgresql:
  image: postgres
  postgresUser: postgres
  postgresPassword: password
  postgresDatabase: mydb
  apiVersion: v1
  kind: Service
  name: postgres
  port: 5432
  replicas: 1
